### PR TITLE
Update to Go 1.17

### PR DESCRIPTION
**Pull request by andrerfcsantos**
Part of https://github.com/exercism/go/issues/1881

Related PR's:

* https://github.com/exercism/go-test-runner/pull/57
* https://github.com/exercism/go-representer/pull/12

### CODE REVIEW

**Review by ErikSchierboom — APPROVED** [review]

**Review by junedev — CHANGES_REQUESTED** [review]
Sorry that it took me so long to start reviewing this. Here my initial findings:
* This repo includes dependencies. Please run go mod vendor and go mod tidy (with go 1.17) to adjust the go.mod and go.sum file to the 1.17 version. (Without that, it gives me an error `go: vendored module github.com/davecgh/go-spew@v1.1.1 should be required explicitly in go.mod`)
* Would be great if you could also add the vendor folder to the gitignore file, it is currently missing there.
* Did you get the tests to pass? If yes, how? They fail for me. However this seems unrelated to the Go version update.
(I might add more comments later if anything else comes up.)

**Comment by andrerfcsantos** [comment]
Thanks for taking a look at this.

I'll go over this in more detail over the weekend and will keep you posted.

**Comment by andrerfcsantos** [comment]
@junedev Ran `go mod vendor && go mod tidy` and also updated gitignore to include the vendoring directory and binaries from `go build`.

I ran the tests with `go test` and they do seem to be failing. However, they are failing for the same reason in our current `main`. Seems like something we must look at, but I don't think it should be a blocker for this PR.

**Review by junedev — APPROVED** [review]

**Comment by junedev** [comment]
Thanks for the update and checking regarding the failing test. Feel free to merge this but please create an issue for the failing test cases if there isn't already one.

**Comment by andrerfcsantos** [comment]
Issue for the failing tests: https://github.com/exercism/go-analyzer/issues/29

**Pull request merged**
